name: Mirror to Azure Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Azure Repos
        run: |
          git remote add azure https://${{ secrets.AZURE_PAT }}@dev.azure.com/MRTB-Licensing-Project/MRTB%20Licensing%20Project/_git/MRTB-Accreditaion-FE
          git push azure --all
          git push azure --tags
